class User < ApplicationRecord
    has_secure_password
    has_many :items
    has_many :stores, through: :items
    has_one :address
    accepts_nested_attributes_for :address


    # def authenticate(password)
    #     return true
    # end
    # def authenticate(password)
    #     # Salts generated by generate_salt are always 29 chars long.
    #     salt = password_digest[0..28]
    #     hashed = BCrypt::Engine::hash_secret(password, salt)
    #     return nil unless (salt + hashed) == self.password_digest
    # end
end
